server:
  port: 8090
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/sbb_dev
    username: root
    password:
  jpa:
    hibernate:
#      ddl-duto create??? ?????????? eb ??? update?? ????
      ddl-auto: update
    show-sql: true